"""add_app_metadata

Revision ID: 4ce9d3e29956
Revises: 6b7324298e84
Create Date: 2026-09-29 11:21:55.174744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce9d3e29956'
down_revision: Union[str, None] = '6b7324298e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vmtopology_enum = sa.Enum('shared', 'per_team', 'per_user', 'custom', name='vmtopology')
    vmtopology_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('apps', sa.Column('vm_topology', vmtopology_enum, nullable=True))
    op.add_column('apps', sa.Column('requirements', sa.Text(), nullable=True))
    op.add_column('apps', sa.Column('recommended_for', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'recommended_for')
    op.drop_column('apps', 'requirements')
    op.drop_column('apps', 'vm_topology')
    sa.Enum(name='vmtopology').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
